export const AUTH = 'AUTH';
export const GET_REALTIME_CHANNELS = 'GET_REALTIME_CHANNELS';
export const SELECT_CHANNEL = 'SELECT_CHANNEL';
export const GET_REALTIME_MEMBERS = 'GET_REALTIME_MEMBERS';
export const GET_REALTIME_MESSAGES_BY_CHANNEL = 'GET_REALTIME_MESSAGES_BY_CHANNEL';
export const GET_ALL_MEMBERS = 'GET_ALL_MEMBERS';
export const PUSH_CHANNEL_ON_TOP = 'PUSH_CHANNEL_ON_TOP';
